version: '2'

networks:
  172.31.0.0:
    external: true

services:
  basic_service:
    build:
      dockerfile: docker/Dockerfile.dev
      context: .
    restart: always
    volumes:
      - ./symfony:/var/www/symfony
    container_name: basic_service
    hostname: basic_service
    environment:
      - REDIS_ADDR=redis://basic_redis
      - DATABASE_URL=postgres://test:test@basic_postgres:15432/test?serverVersion=12&charset=utf8

    ports:
    - 9191:9000
    links:
      - basic_postgres
      - basic_redis
    networks:
      - 172.31.0.0

  basic_redis:
    image: redis:5.0.7
    hostname: basic_redis
    container_name: basic_redis
    networks:
      - 172.31.0.0

  basic_postgres:
    image: postgres:12.4-alpine
    hostname: basic_postgres
    container_name: basic_postgres
    restart: always
    ports:
      - 15432:5432
    networks:
      - 172.31.0.0
    environment:
      - "POSTGRES_USER=test"
      - "POSTGRES_PASSWORD=test"